create database supermarket;
use supermarket;
drop database supermarket;
show tables;
select*from supermarket_sales limit 20;
select*from sales;

DESCRIBE supermarket_sales;
#-----------------------------------------------------------------------------------------------------------
#1. Which city has the highest total revenue?
select city,round(sum(total),2) as total_revenue from supermarket_sales group by city order by total_revenue desc;

#2. What is the most frequently purchased product line?
select product_line, count(product_line) as Most_Frequently_Purchased from supermarket_sales 
group by Product_line order by Most_Frequently_Purchased desc;

#3. What is the average rating given by customers in each city?
select city, round(avg(rating),2) as Avg_Rating_Citywise from supermarket_sales group by city
order by Avg_Rating_Citywise desc;

#4. How many transactions were done using each payment method?
select payment, count(payment) as total_transcation from supermarket_sales group by payment;

#5. What is the total gross income generated by each product line?
select product_line, round(sum(gross_income),2) as total_gross_income from supermarket_sales
group by product_line order by total_gross_income desc;

#6. Which customer type contributes more to overall sales?
select customer_type, round(sum(total),2) as total_Sales from supermarket_sales
group by customer_type order by total_Sales desc;

#7. On which date was the highest revenue recorded?
select date, round(sum(total),2) as highest_revenue from supermarket_sales group by date order by
highest_revenue desc limit 1;

#8. What is the average unit price for each product line?
select product_line, round(avg(unit_price),2) as avg_unit_price from supermarket_sales
group by Product_line order by avg_unit_price desc;

#9. Which product line has the highest average gross income per transaction?
select product_line, round(avg(gross_income),2) as high_avg_gross_income from supermarket_sales
group by product_line order by high_avg_gross_income desc limit 1;

#10. How do total sales vary across weekdays (Mon–Sun)?
SELECT DAYNAME(date) AS weekday, ROUND(SUM(total), 2) AS total_sales FROM supermarket_sales GROUP BY weekday
ORDER BY FIELD(weekday, 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday');

#11. What is the average transaction value for each customer type?
select customer_type, round(avg(total),2) as avg_transaction_value from supermarket_sales group by Customer_type;

#12. Which product line has the lowest average rating despite good revenue?
WITH revenue_stats AS (SELECT product_line,ROUND(AVG(rating), 2) AS avg_rating,
ROUND(SUM(total), 2) AS total_revenue FROM supermarket_sales GROUP BY product_line)
SELECT *FROM revenue_stats WHERE total_revenue > (SELECT AVG(total_revenue) FROM revenue_stats);

#13. What are the top 3 grossing product lines in each city?
SELECT *FROM (SELECT city,product_line,ROUND(SUM(total), 2) AS total_revenue,
RANK() OVER (PARTITION BY city ORDER BY SUM(total) DESC) AS rank_in_city FROM supermarket_sales GROUP BY city, product_line
) AS ranked_data WHERE rank_in_city <= 3 ORDER BY city, rank_in_city;

#14. Which product line shows high quantity sales but low gross income — indicating low profit margin?
SELECT product_line,SUM(quantity) AS total_quantity,ROUND(SUM(gross_income), 2) AS total_gross_income
FROM supermarket_sales GROUP BY product_line ORDER BY total_quantity DESC, total_gross_income ASC;

#15.What is the contribution (%) of each product line to the total revenue in each city?
SELECT city,product_line,round(SUM(total),2) AS total_revenue FROM supermarket_sales GROUP BY city, product_line
ORDER BY city, total_revenue DESC;


